# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Prompt format
format = """
$hostname\
$env_var\
$username\
$sudo\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$direnv\
$localip\
$singularity\
$kubernetes\
$vcsh\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$jobs\
$status\
$os\
$container\
$battery\
$time\
$jobs\
$shell\
$cmd_duration
$character
"""

# primary keys
continuation_prompt = '▶▶ '
add_newline = false
command_timeout = 2000

# general
[line_break]
disabled = true


# the actual prompt
[character]
format = "$symbol "
success_symbol = '[󰜴](bold green) '
error_symbol = '[󰜴](bold red) '

# left prompt
[hostname]
ssh_symbol = " "
disabled = true

# why is this here?
[env_var.VIMSHELL] # vim subshell
format = " [$env_value]($style)"
style = 'green italic'
disabled = true

[username]
style_user = "yellow bold"
style_root = "purple bold italic"
format = " [$user]($style) ▻ "
disabled = true

[sudo]
format = " [$symbol]($style)"
style = "italic bright-purple"
symbol = "◇┈"
disabled = true

# spaces for bizarre left truncation
[directory]
read_only = " 󰌾"
fish_style_pwd_dir_length = 3
truncation_length = 3
truncate_to_repo = false
use_logical_path = false
truncation_symbol = "xxx"
repo_root_format = 'GIT:[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = " "
format = " [ $symbol $branch(:$remote_branch)]($style)"
style = "bold italic white"

[git_status]
style = "italic bright-blue"
format = """([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"""
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▲│[${count}](bold white)│](italic green)"
behind = "[▽│[${count}](bold white)│](italic red)"
diverged = "[◇ ▲┤[${ahead_count}](regular white)│▽┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◦◫◦](italic white)"
modified = "[●◦](italic yellow)"
staged = "[■┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"

# fill
[fill]
symbol = " "
style = "yellow"
disabled = false

# right prompt

[direnv]
disabled = false

[gcloud]
format = '[$symbol$active]($style) '
style = 'bold yellow'
disabled = true

[shlvl]
disabled = true
format = '[$symbol]($style) '
threshold = 1
repeat = true

[shell]
fish_indicator = ''
bash_indicator = ''
zsh_indicator = 'z'
unknown_indicator = ''
format = " [$indicator $name]($style) "
style = 'cyan bold'
disabled = false

[status]
disabled = false
format = '[ $symbol $status - $common_meaning](green)'
map_symbol = true

[aws]
symbol = " "
format = ' [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "italic blue"
force_display = true
[aws.profile_aliases]
nb = 'nb'

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"


[time]
disabled = false
format = " [ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[battery]
format = " [ $percentage $symbol]($style)"
full_symbol = "[█](italic green)"
charging_symbol = "[↑](italic green)"
discharging_symbol = "[↓](italic)"
unknown_symbol = "[░](italic)"
empty_symbol = "[▃](italic red)"

[[battery.display]]
threshold = 40
style = "dimmed yellow"

[[battery.display]]
threshold = 70
style = "dimmed white"

[localip]
ssh_only = true
format = " ◯ [$localipv4](magenta)"
disabled = false

[cmd_duration]
min_time = 0
show_milliseconds = true
show_notifications = true
min_time_to_notify = 45_000
format = " [$duration ](italic bright-yellow)"


[jobs]
format = " [ $symbol$number]($style)"
style = "white"
symbol = "[▶ ](blue italic)"

[lua]
symbol = " "
format = " lua [${symbol}${version}]($style)"
style = "italic bright-yellow"

[python]
symbol = " "
format = " py [${symbol}${version}]($style)"
version_format = "${major}.${minor}"
style = "italic bright-yellow"

[perl]
symbol = " "

[pijul_channel]
symbol = " "

[ocaml]
symbol = " "

[swift]
symbol = " "
format = " sw [${symbol}${version}]($style)"
style = "italic bright-red"
version_format = "${major}.${minor}"

[deno]
format = " deno [∫ $version](blue italic)"
version_format = "${major}.${minor}"

[c]
symbol = " "
format = " c [$symbol($version(-$name))]($style)"

[dart]
symbol = " "
format = " dart [$symbol($version )]($style)"

[julia]
symbol = " "
format = " jl [$symbol($version )]($style)"

[package]
symbol = "󰏗 "
format = " pkg [$symbol$version]($style)"
version_format = "${major}.${minor}"
style = "bright-yellow italic"

[crystal]
symbol = " "

[fennel]
symbol = " "

[haxe]
symbol = " "

[elm]
symbol = "◩ "
format = " elm [$symbol($version )]($style)"

[guix_shell]
symbol = " "

[buf]
symbol = " "
format = " buf [$symbol $version $buf_version]($style)"

[nim]
symbol = "󰆥 "
format = " nim [$symbol($version )]($style)"

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"

[rust]
symbol = " "
format = " rs [$symbol$version]($style)"
version_format = "${major}.${minor}"
style = "italic red"

[kotlin]
symbol = " "

[elixir]
symbol = " "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[golang]
symbol = " "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = " "
format = " hs [$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
format = " mem [${ram}( ${swap})]($style)"

[nix_shell]
symbol = " "
format = " nix [$symbol$state $name]($style)"

[nodejs]
symbol = " "
format = " [$symbol ($version)](italic bright-green)"
detect_files = ["package-lock.json", "yarn.lock"]
version_format = "${major}.${minor}"

[ruby]
symbol = " "
format = " rb [${symbol}${version}]($style)"
version_format = "${major}.${minor}"
style = "italic red"

[rlang]
symbol = "󰟔 "

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[meson]
symbol = "󰔷 "

[scala]
symbol = " "

[php]
symbol = " "

[zig]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
